name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install fontconfig
      run: sudo apt-get update && sudo apt-get install -y pkg-config libfontconfig1-dev

    # build with no features
    - name: build no features
      run: cargo build --no-default-features

    # build with just plotting feature
    - name: build plotting tests
      run: cargo build --features "plotting"

    # build tests with just transforms feature
    - name: build transforms tests
      run: cargo build --features "transforms"

    # Run tests with all features
    - name: Run complete tests
      run: cargo test --all-features --lib
